baseURL: "https://30DaysofMH.com/"
title: 30DaysofMH
paginate: 5
theme: hugo-PaperMod-7.0

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        # menu:
            #main:
              #  - name: About
                  #url: about
                  #weight: 2
              #  - name: Archive
                  #url: archives
                  #weight: 4
               # - name: Now
                  #url: now
                  #weight: 1
                #- name: Evergreen
                  #url: evergreen
                  #weight: 3
                #- name: Tags
                  #url: tags/
                  #weight: 10
                #- name: Categories
                  #url: categories/
                  #weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "30 Days of Monster Hunter Challenges with Ristretto"
    author: Ristretto
    # author: ["Ristretto", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    #ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    # images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: 30DaysofMH
        imageUrl: "/icon.png"
        imageTitle: my image
         #imageWidth: 72
         #imageHeight: 72
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        #Title: "RistrettoRambles"
        Content: >
            ## Ahoy & welcome to the "30 Days of Lance" challenge!

            For the next 30 days of my streams on Twitch I'll be using only Lance in Monster Hunter Rise: Sunbreak. It's currently one of my least-played weapons in the 1300 hours I've played of Sunbreak, so my aim for the next 30 streams is to give myself challenges that will force me to learn a lot more about it, try a variety of aspects of the weapon, and hopefully improve quickly.
            <br />
            <br />

            **Our challenges will be:**
            <br />
            - Use only Lance for 30 days of streaming (excepting gathering and cycling quests).
            <br />
            - Add at least 205 Lance hunts to my guild card (for a total of 300) by the end of the 30 days.
            <br />
            - Clear the game's entire roster of 76 monsters with Lance at least once, aiming to clear an Anomaly or otherwise tough Master Rank version of the monster whenever possible.
            <br />
            - Clear all Master Rank event quests with Lance.
            <br />
            - Use randomized loadouts of switch skills each night for the first 15 nights of the challenge, with the last 15 days being "anything goes".
            <br />
            - Make at least 4 armor sets I'm happy with: Meta Raw, Meta Element, Off-Meta "Goofy", and a favorite most "me-feeling" set.
            <br />
            - Collect one lance for each element, status, and one more pure-raw option.
            <br />
            - Complete a sub-10 Anomaly hunt of my choosing.
            <br />
            - Complete a final, ultimate challenge of my choosing (to be decided much later into the challenge).
            <br />
            <br />

            Follow along with my nightly progress in the [Progress Log](progresslog).
            <br />
            <br />


           

            - Thanks for visiting!

    socialIcons:
        - name: twitch
          url: "http://twitch.tv/ristrettorambles/"
        - name: discord
          url: "https://discord.gg/f2QmzbH"
        - name: mastodon
          url: "https://mastodon.social/@Ristretto"
        - name: youtube
          url: "https://www.youtube.com/channel/UCgg0KncWzZobxuy3nO0xRuQ"
        #- name: RsS
          #url: "index.xml"

    #editPost:
        #URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        #Text: "Suggest Changes" # edit text
        #appendFilePath: true # to append file path to Edit link


label:
   text: "Home"
   icon: "/icon.png"
   iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.ico"
    apple_touch_icon: "/apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#fuseOpts:
    #isCaseSensitive: false
    #shouldSort: true
    #location: 0
    #distance: 1000
    #threshold: 0.4
    #minMatchCharLength: 0
    #keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

